# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('catalog', '0002_catalogmainpage_catalogproductpage_catalogtilespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProductPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('caption_small', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='catalogproductpage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Опис продукту'),
        ),
        migrations.AddField(
            model_name='catalogproductpagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.CatalogProductPage'),
        ),
    ]
