# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('catalog', '0003_auto_20170901_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogTilesPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='catalogproductpagegalleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='catalogproductpagegalleryimage',
            name='caption_small',
        ),
        migrations.RemoveField(
            model_name='catalogtilespage',
            name='intro',
        ),
        migrations.AddField(
            model_name='catalogtilespage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(default='ADD DESCRIPTION', verbose_name='Опис розділу'),
        ),
        migrations.AddField(
            model_name='catalogtilespagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.CatalogTilesPage'),
        ),
    ]
