# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170902_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogindexpage',
            options={'verbose_name': 'Сторінка каталогу виробника, або можете використати як вкладений каталог (Вкладений каталог)'},
        ),
        migrations.AlterModelOptions(
            name='catalogmainpage',
            options={'verbose_name': 'Сторінка головного каталогу, НЕ СТВОРЮЙТЕ ЦЮ СТОРІНКУ (Головний каталог)'},
        ),
        migrations.AlterModelOptions(
            name='catalogproductpage',
            options={'verbose_name': 'Кінцева сторінка продукту (Сторінка продукту)'},
        ),
        migrations.AlterModelOptions(
            name='catalogtilespage',
            options={'verbose_name': 'Сторінка-каталог у вигляді тайлів, для однотипної продукції (Каталог-тайли)'},
        ),
    ]
