# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogindexpagegalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogindexpage',
            old_name='intro',
            new_name='description',
        ),
        migrations.AddField(
            model_name='catalogindexpage',
            name='short_title',
            field=models.CharField(default='Manufacturer', max_length=90),
        ),
        migrations.AddField(
            model_name='catalogindexpage',
            name='sphere',
            field=models.CharField(default='Medicine', max_length=90),
        ),
    ]
